### ISSUE TITLE
ValueError: Failed to concatenate on axis=1 because tables don't have the same number of rows

### ISSUE THREAD

**Issue by ganga7445** [tomaarsen/SpanMarkerNER#38]
When I place a single word in the first index of the list, it leads to the above error. However, if I put it in any index other than the first, no error occurs.

from span_marker import SpanMarkerModel
model = SpanMarkerModel.from_pretrained("tomaarsen/span-marker-bert-base-fewnerd-fine-super")
entities = model.predict( ['Avolon', 'Walmart - Milwaukee, WI'])   **#error**
entities = model.predict( [ 'Walmart - Milwaukee, WI','Avolon'])  **#no error**
Can you please help me here  @tomaarsen

**Comment by michaelrhanson** [comment]
I am also hitting this error, with a different pretrained model.  It appears to occur with only certain combinations of entities and inputs; the class does not appear to matter.

```
model_name = "tomaarsen/span-marker-roberta-large-ontonotes5"
model = span_marker.SpanMarkerModel.from_pretrained(model_name)
cpuModel.predict(["yahoo.com", "The Prince of Wales."])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/project/lib/python3.10/site-packages/span_marker/modeling.py", line 465, in predict
    dataset = dataset.add_column(key, value)
  File "~/project/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "~/project/lib/python3.10/site-packages/datasets/fingerprint.py", line 511, in wrapper
    out = func(dataset, *args, **kwargs)
  File "~/project/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 5621, in add_column
    table = concat_tables([dataset._data, column_table], axis=1)
  File "~/project/lib/python3.10/site-packages/datasets/table.py", line 1802, in concat_tables
    return ConcatenationTable.from_tables(tables, axis=axis)
  File "~/project/lib/python3.10/site-packages/datasets/table.py", line 1507, in from_tables
    blocks = _extend_blocks(blocks, table_blocks, axis=axis)
  File "~/project/lib/python3.10/site-packages/datasets/table.py", line 1499, in _extend_blocks
    result, blocks = _split_both_like(result, blocks)
  File "~/project/lib/python3.10/site-packages/datasets/table.py", line 1489, in _split_both_like
    raise ValueError("Failed to concatenate on axis=1 because tables don't have the same number of rows")
ValueError: Failed to concatenate on axis=1 because tables don't have the same number of rows
```

**Comment by michaelrhanson** [comment]
Digging deeper into the problem in `modeling.py`, it appears that this is a problem when we are processing a list of strings, and one of the strings is tokenized to a single token.  It _looks_ like we are getting a singleton back and that a list concatenation is going off the rails:
```
>>> model.predict(["yahoo.com test", "The Prince of Wales."])
Tokenizer dict: {'input_ids': [[0, 1423, 36055, 4, 175, 1296, 2], [0, 20, 2804, 9, 5295, 4, 2]], 'num_spans': [10, 15], 'start_position_ids': [[1, 1, 1, 1, 3, 3, 3, 4, 4, 5], [1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5]], 'end_position_ids': [[2, 3, 4, 5, 3, 4, 5, 4, 5, 5], [1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5]], 'num_words': [4, 5]}

>>> model.predict(["yahoo.com", "The Prince of Wales."])
Tokenizer dict: {'input_ids': [[0, 1423, 36055, 4, 175, 20, 2804, 9, 5295, 4, 2]], 'num_spans': [3], 'start_position_ids': [[1, 1, 5]], 'end_position_ids': [[4, 9, 9]], 'num_words': [2]}
```

**Comment by michaelrhanson** [comment]
@tomaarsen It looks like the `is_split_into_words` check on tokenizer.py:165, is, as your comment suggests, not robust enough.

Specifically, when we pass a single sentence that contains no whitespace along with other sentences that _do_ contain whitespace, the `is_split_into_words` flag is different across the batch, leading to different outputs from the tokenizer.

One fix would be to check all the strings instead of assuming the first one will be an indicator for the whole list (sorry, don't have time to pull together a PR at this instant):
```
if isinstance(tokens, str):
            is_split_into_words = False
        elif tokens:
            for t in tokens:
                if " " in t:
                    is_split_into_words = False
                    break
```
