### ISSUE TITLE
Error loading SpanMarkerTokenizer

### ISSUE THREAD

**Issue by polodealvarado** [tomaarsen/SpanMarkerNER#44]
Hello Tom.

I have found a problem when loading the tokenizer directly from the SpanMarkerTokenizer class.

### **System Info**
Platform: MacOS Sonoma 14.0, M1 Pro
Python 3.11.5

transformers=4.35.0
span_marker=1.5.0
tokenizers=0.14.1

### **Error Response**
```
tokenizer = SpanMarkerTokenizer.from_pretrained("tomaarsen/span-marker-mbert-base-multinerd")
Downloading (…)okenizer_config.json: 100%|███| 343/343 [00:00<00:00, 834kB/s]
Downloading (…)solve/main/vocab.txt: 100%|█| 996k/996k [00:00<00:00, 3.36MB/s
Downloading (…)/main/tokenizer.json: 100%|█| 2.92M/2.92M [00:00<00:00, 5.46MB
Downloading (…)in/added_tokens.json: 100%|█| 43.0/43.0 [00:00<00:00, 114kB/s]
Downloading (…)cial_tokens_map.json: 100%|███| 125/125 [00:00<00:00, 384kB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/polodealvarado/Desktop/github_projects/SpanMarkerNER/span_marker/tokenizer.py", line 285, in from_pretrained
    return cls(tokenizer, config=config, **kwargs)
  File "/Users/polodealvarado/Desktop/github_projects/SpanMarkerNER/span_marker/tokenizer.py", line 156, in __init__
    self.tokenizer.model_max_length, self.config.model_max_length or self.config.model_max_length_default
AttributeError: 'NoneType' object has no attribute 'model_max_length'
```

### **Expected behaviour**
Get the tokenizer

**Comment by tomaarsen** [comment]
You're right! Well spotted. The tokenizer `from_pretrained` expects there to always be a config, e.g. like so:
```python
from span_marker.tokenizer import SpanMarkerTokenizer
from span_marker import SpanMarkerConfig

repo_id = "tomaarsen/span-marker-mbert-base-multinerd"
config = SpanMarkerConfig.from_pretrained(repo_id)
tokenizer = SpanMarkerTokenizer.from_pretrained(repo_id, config=config)
```

The fix should be fairly straightforward, e.g. adding 
```python
        if config is None:
            config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
```
just before the return statement in  `SpanMarkerTokenizer.from_pretrained`. I'll try to get a fix out for this soon, but you can apply one of these workarounds if they're preventing you from proceeding otherwise.

- Tom Aarsen

**Comment by polodealvarado** [comment]
Great! Thank you for response.
