### ISSUE TITLE
AttributeError: 'RobertaTokenizerFast' object has no attribute 'pad_token_id'. Did you mean: 'pad_token_type_id'?

### ISSUE THREAD

**Issue by nickludlam** [tomaarsen/SpanMarkerNER#70]
I'm running span marker 1.6.0 and I've just updated to transformers 4.47.0.  When calling `span_marker_model.predict(sentence)` I'm now seeing the following exception:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/code/lib/python3.12/site-packages/span_marker/tokenizer.py", line 174, in __getattribute__
    return super().__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SpanMarkerTokenizer' object has no attribute 'pad_token_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/extract_entities.py", line 32, in run
    self.last_result = self.entity_extractor.extract_entities(sentence)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/ner/span_marker_model.py", line 37, in extract_entities
    entities = self.span_marker_model.predict(sentence)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/code/lib/python3.12/site-packages/span_marker/modeling.py", line 509, in predict
    batch = self.data_collator(batch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/code/lib/python3.12/site-packages/span_marker/data_collator.py", line 73, in __call__
    input_ids = F.pad(input_ids, (0, total_size - len(input_ids)), value=self.tokenizer.pad_token_id)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/code/lib/python3.12/site-packages/span_marker/tokenizer.py", line 176, in __getattribute__
    return super().__getattribute__("tokenizer").__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RobertaTokenizerFast' object has no attribute 'pad_token_id'. Did you mean: 'pad_token_type_id'?```
```

I can manually patch the code to convert it during runtime with the following, but I don't feel like this is a good solution, and I cannot trace through transformers why this issue has occurred with their recent changes.

```py
def find_pad_token_id(self):
    pad_token = self.tokenizer.pad_token
    return self.tokenizer.convert_tokens_to_ids(pad_token)
```

**Comment by omri374** [comment]
I have the same issue

**Comment by sanmai-NL** [comment]
I have the same issue with the BERT tokenizer.

**Comment by tomaarsen** [comment]
I'm getting the same now - the issue was introduced in `transformers` 4.47.0 I believe. For now I'm using `transformers<4.47.0` until I have some more time to fix this.

- Tom Aarsen
